// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zranlyfjdzzqbcfxffjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyYW5seWZqZHp6cWJjZnhmZmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDIyNTUsImV4cCI6MjA2MDYxODI1NX0.OpkkMpt_vbDfMx7QqJMmZXEIhyP_rurMT5xZaULYQuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);